---
- name: "vars: show variables"
  tags: vars
  hosts: all
  gather_facts: false
  tasks:
    - debug:
        var: vars
- name: "ping: check all hosts"
  tags: ping
  hosts: all
  tasks:
    - name: "ping"
      ansible.builtin.ping:
- name: "wine: install wine"
  tags: wine
  hosts: wine_hosts
  roles:
    - name: ansible-role-wine
